# permissions for end users to edit teams.
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: harmonizer
    app.kubernetes.io/managed-by: kustomize
  name: team-editor-role
rules:
- apiGroups:
  - harmonizer.io
  resources:
  - teams
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - harmonizer.io
  resources:
  - teams/status
  verbs:
  - get
